replicaCount: 1
image:
  repository: 558207650175.dkr.ecr.eu-west-1.amazonaws.com/xooi-integration-prod
  pullPolicy: Always
  tag: build-3e1e8ede-aa55-4592-87c3-714c3c326114
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  clusterIP: 172.20.7.41
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: musoshi-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
    - host: nbs-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
    - host: netlog-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
    - host: our-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
    - host: pts-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
nodeSelector:
  role: general
tolerations: []
affinity: {}
resources:
  limits:
    memory: 390Mi
  requests:
    cpu: 14m
    memory: 390Mi
