version: '3'
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      npm: null

  derper:
#    build: .
    image: bariiss/derper:amd64 # or amd64
    restart: always
    container_name: derper
    hostname: derp.latte.ltd
    ports:
      - 3439:3439/udp
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    networks:
      npm: null

networks:
  npm:
    name: npm
