replicaCount: 1
image:
  repository: 558207650175.dkr.ecr.eu-west-1.amazonaws.com/xooi-eventhandler-prod
  pullPolicy: Always
  tag: build-a241cd61-d9c9-4e8f-a16c-2c6ed759ce0d
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  clusterIP: 172.20.110.10
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/group.name: api-xooi-internal-prod
    alb.ingress.kubernetes.io/load-balancer-name: api-xooi-internal-prod
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:558207650175:certificate/ed2ee47a-f4df-4d07-a51a-3ffedc06e04f
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
  hosts:
    - host: hangfire.xooi.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  limits:
    memory: 306Mi
  requests:
    cpu: 82m
    memory: 306Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
nodeSelector:
  role: general
tolerations: []
affinity: {}
