replicaCount: 1
image:
  repository: 558207650175.dkr.ecr.eu-west-1.amazonaws.com/xooi-cx-mail-prod
  pullPolicy: Always
  tag: build-c3fb1f3c-f0d5-4553-99a1-af7b5c31d13b
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  clusterIP: 172.20.220.38
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/group.name: api-xooi-internal-prod
    alb.ingress.kubernetes.io/load-balancer-name: api-xooi-internal-prod
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:558207650175:certificate/ed2ee47a-f4df-4d07-a51a-3ffedc06e04f
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
  hosts:
    - host: cx-mail.xooi.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  limits:
    memory: 313Mi
  requests:
    cpu: 36m
    memory: 313Mi
autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector:
  role: general
tolerations: []
affinity: {}
