apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "xooi-metabase-palex.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "xooi-metabase-palex.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "xooi-metabase-palex.selectorLabels" . | nindent 6 }}
  strategy:
    blueGreen:
      activeService: {{ include "xooi-metabase-palex.fullname" . }}
      previewService: {{ include "xooi-metabase-palex.fullname" . }}-preview
      autoPromotionEnabled: true
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- .Values.podLabels | toYaml | nindent 8 }}
        {{- include "xooi-metabase-palex.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xooi-metabase-palex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: "xooi-utility-prod"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 40
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 