apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "xooi-webhook-prod.fullname" . }}
  labels:
    {{- include "xooi-webhook-prod.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "xooi-webhook-prod.selectorLabels" . | nindent 6 }}
  strategy:
    blueGreen:
      activeService: {{ include "xooi-webhook-prod.fullname" . }}
      previewService: {{ include "xooi-webhook-prod.fullname" . }}-preview
      autoPromotionEnabled: false
      previewReplicaCount: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xooi-webhook-prod.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xooi-webhook-prod.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: "xooi-utility-prod"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 15
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 15
          periodSeconds: 10
          failureThreshold: 10
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}