replicaCount: 2
image:
  repository: 558207650175.dkr.ecr.eu-west-1.amazonaws.com/xooi-file-upload-prod
  pullPolicy: Always
  tag: build-d6692e0e-7f2b-434a-a195-375bdd6cb171
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext:
  runAsUser: 1000
service:
  type: ClusterIP
  port: 80
  targetPort: 5004
  clusterIP: 172.20.48.188
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: musoshi-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
    - host: nbs-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
    - host: netlog-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
    - host: our-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
    - host: pts-api.xooi.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
nodeSelector:
  role: general
tolerations: []
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - xooi-file-upload-prod
        topologyKey: kubernetes.io/hostname
resources:
  limits:
    memory: 244Mi
  requests:
    cpu: 17m
    memory: 244Mi
