name: Multi-Arch Docker Image CI

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: vdf
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ vars.GO_VERSION }}

    - name: Fetch all tags
      run: |
        git fetch --tags
        echo "TAGS=$(git tag -l)"
        echo "Available tags: $(git tag -l)" >> $GITHUB_ENV

    - name: Get latest version tag
      id: get-latest-tag
      run: |
        # Fetching the latest version tag using Go modules (adjust GO_REPO if necessary)
        LATEST_TAG=$(go list -m -versions ${{ vars.GO_REPO }} | tr ' ' '\n' | grep -v '\-pre' | sort -V | tail -n 1)
        echo "LATEST_TAG=$LATEST_TAG"
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

    - name: Check if tag exists locally
      id: tag-check-local
      run: |
        echo "Checking if tag ${{ steps.get-latest-tag.outputs.LATEST_TAG }} exists locally"
        git rev-parse "refs/tags/${{ steps.get-latest-tag.outputs.LATEST_TAG }}" >/dev/null 2>&1
        TAG_EXISTS=$?
        echo "Local tag existence status: $TAG_EXISTS"
        if [ $TAG_EXISTS -eq 0 ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Check if tag exists remotely
      id: tag-check-remote
      run: |
        echo "Checking if tag ${{ steps.get-latest-tag.outputs.LATEST_TAG }} exists remotely"
        git ls-remote --tags origin | grep "refs/tags/${{ steps.get-latest-tag.outputs.LATEST_TAG }}"
        REMOTE_TAG_EXISTS=$?
        echo "Remote tag existence status: $REMOTE_TAG_EXISTS"
        if [ $REMOTE_TAG_EXISTS -eq 0 ]; then
          echo "remote_exists=true" >> $GITHUB_OUTPUT
        else
          echo "remote_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Remove if tag exists locally and remotely
      if: steps.tag-check-local.outputs.exists == 'true' || steps.tag-check-remote.outputs.remote_exists == 'true'
      run: |
        if [ "${{ steps.tag-check-local.outputs.exists }}" == "true" ]; then
          echo "Deleting local tag ${{ steps.get-latest-tag.outputs.LATEST_TAG }}"
          git tag -d ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
        fi
        if [ "${{ steps.tag-check-remote.outputs.remote_exists }}" == "true" ]; then
          echo "Deleting remote tag ${{ steps.get-latest-tag.outputs.LATEST_TAG }}"
          git push --delete origin ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
        fi

    - name: Skip build if tag exists
      if: steps.tag-check-local.outputs.exists == 'true' || steps.tag-check-remote.outputs.remote_exists == 'true'
      run: echo "Skipping build as the tag already exists."

    - name: Set up QEMU
      if: steps.tag-check-local.outputs.exists != 'true' && steps.tag-check-remote.outputs.remote_exists != 'true'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: steps.tag-check-local.outputs.exists != 'true' && steps.tag-check-remote.outputs.remote_exists != 'true'
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request' && steps.tag-check-local.outputs.exists != 'true' && steps.tag-check-remote.outputs.remote_exists != 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_PAT_TOKEN }}

    - name: Build and push Docker image
      if: steps.tag-check-local.outputs.exists != 'true' && steps.tag-check-remote.outputs.remote_exists != 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.get-latest-tag.outputs.LATEST_TAG }}
        build-args: |
          BUILDPLATFORM=${{ runner.os }}/${{ runner.arch }}
          NO_CACHE=${{ vars.NO_CACHE }}

    - name: Create Git tag
      if: steps.tag-check-local.outputs.exists != 'true' && steps.tag-check-remote.outputs.remote_exists != 'true' && success()
      run: |
        git config user.name ${{ github.actor }}
        git config user.email ${{ vars.GIT_EMAIL }}
        git tag ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
        git push origin ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
