name: Multi-Arch Docker Image CI

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NO_CACHE: true

jobs:
  build-and-push:
    runs-on: vdf
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch all tags
      run: git fetch --tags

    - name: Get latest version tag
      id: get-latest-tag
      run: |
        LATEST_TAG=$(go list -m -versions tailscale.com | tr ' ' '\n' | grep -v '\-pre' | sort -V | tail -n 1)
        echo "::set-output name=LATEST_TAG::${LATEST_TAG}"

    - name: Check if tag exists
      id: tag-check
      run: |
        if git rev-parse "refs/tags/${{ steps.get-latest-tag.outputs.LATEST_TAG }}" >/dev/null 2>&1; then
          echo "Tag ${{ steps.get-latest-tag.outputs.LATEST_TAG }} already exists."
          echo "::set-output name=exists::true"
        else
          echo "Tag ${{ steps.get-latest-tag.outputs.LATEST_TAG }} does not exist."
          echo "::set-output name=exists::false"
        fi

    - name: Skip build if tag exists
      if: steps.tag-check.outputs.exists == 'true'
      run: echo "Skipping build as the tag already exists."

    - name: Set up QEMU
      if: steps.tag-check.outputs.exists != 'true'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: steps.tag-check.outputs.exists != 'true'
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request' && steps.tag-check.outputs.exists != 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_PAT_TOKEN }}

    - name: Build and push Docker image
      if: steps.tag-check.outputs.exists != 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.get-latest-tag.outputs.LATEST_TAG }}
        build-args: |
          BUILDPLATFORM=${{ runner.os }}/${{ runner.arch }}
          NO_CACHE=${{ env.NO_CACHE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create Git tag
      if: steps.tag-check.outputs.exists != 'true'
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
        git push origin ${{ steps.get-latest-tag.outputs.LATEST_TAG }}